application: 
  annotations:
    argocd.argoproj.io/compare-options: >- 
      ServerSideDiff=true,
      IncludeMutationWebhook=true 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:     
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
    - SkipDryRunOnMissingResource=true
    - ServerSideApply=true

  type: helmRepo # helmChart, helmRepo, manafests

  helmRepo: 
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 18.0.0
    chart: nginx
    values:
      repoURL: git@github.com:graysievert-lab/experiment-k8s-bootstrapping-applicationset-generator-git-file.git
      targetRevision: HEAD
      valueFile: apps/nginx-public/values.yaml
